> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Interesting Numpy Modules


Here ae five short introduction about Numpy and list the chosen functions:

- np.linalg.solve
- np.char.count
- np.place
- np.extract
- np.clip

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [9]:
!pip install jovian --upgrade -q

In [10]:
import jovian

In [11]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dinmdohan813/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/dinmdohan813/numpy-array-operations


'https://jovian.ai/dinmdohan813/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [12]:
import numpy as np

In [13]:
# List of functions explained 
function1 = np.linalg.solve  
function2 = np.char.count
function3 = np.place
function4 = np.extract
function5 = np.clip

## Function 1 - np.linalg.solve

This function falls under the category of linear algebric function. Generally we have to solve liner equations to get the required value. By using this function, we can solve the equations and solve the problems.


In [38]:
# Example 1 - working
a = np.array([[1, 2], 
        [3, 4]])

b = np.array([5, 6])

x=np.linalg.solve(a,b)
x


array([-4. ,  4.5])

This is the example of linear system of equations of two variables.So we get two values as a solution.

In [59]:
# Example 2 - working
c=np.array([[2,4,6],[8,1,9],[3,5,7]])

d=np.array([1,3,5])

y=np.linalg.solve(c,d)

y

array([ 3.93333333,  3.63333333, -3.56666667])

This is the example of linear system of equations of three variables.In this case we get the three solutions.



In [64]:
# Example 3 - breaking 
e =np.array ([[9, 8,3], 
              [2, 4,7],
             [5,7,6]])

f=np.array([3,4])

x=np.linalg.solve(e,f)
x

ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 2 is different from 3)

In this example the number of constant are not equal to the number of system of equations. Thats why this does not work. In order to run it correctly, we have to make the number of constant equal to the number of system of equations.



This function is used generally to solve the system of linear equations. It is a common mathematical operation and reduce the time of operating in calculator.

In [65]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dinmdohan813/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/dinmdohan813/numpy-array-operations


'https://jovian.ai/dinmdohan813/numpy-array-operations'

## Function 2 - np.char.count

This function is used to count the number of single characters in a array. It is useful as it also provide some slicing options as well.


In [55]:
# Example 1 - working
a= np.array(['DiN','MoHAmmAd','dOHAn','sRaBoN'])

np.char.count(a,'n')

array([0, 0, 1, 0])

In this example we randomly form the array of any character and used the function the number of time it was repeated in the given array.



In [56]:
# Example 2 - working
b= np.array(['this is my world','Copt it','Dont ruin it'])

np.char.count(b,'s',start=0,end=5)

array([1, 0, 0])

In this example we use np.char.count function to count the number of characters in the specific item of an array.In this process we also used slicing option to count the specific characters fromthe specific point.In this example we start to count from index position 0 and end at index position 4.

In [57]:
# Example 3 - breaking 
x= np.array(['sHuvrO','mAmUn','TaGore'])

np.char.count(x,'o',start='m',end='e')

TypeError: slice indices must be integers or None or have an __index__ method

In this example we tried to use alphabet instead of integer to define the starting point and ending point of a countingof character process but it terminated without giving result and showed the error message. This is because we cannot use alphabet for slicing.To run it properly we should use integer.

We can find the number of any characters by using np.char.count function in short span of time. It will save our time of seaarching for specific character.

In [58]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dinmdohan813/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/dinmdohan813/numpy-array-operations


'https://jovian.ai/dinmdohan813/numpy-array-operations'

## Function 3 - np.place

This function is used to place some values for the specfic values of the elements of the array.


In [46]:
# Example 1 - working

p=np.array([[5,7],
          [9,2]])

np.place(p,p==5,8)

p

array([[8, 7],
       [9, 2]])

In this example we create a array, then we like to replace the elements of array with some specific element. So we put a condition in which if the element of array is equal to 5 it would be replaced by number 8.

In [68]:
# Example 2 - working

x=np.arange(9).reshape(3,3)

np.place(x,x>4,[11,44])
x
  

array([[ 0,  1,  2],
       [ 3,  4, 11],
       [44, 11, 44]])

It is a little bit of advaned form of previous example. In this example we create a (3,3) array then put on a condition in which if number is greater than 4, it would be replaced by the series of number 11 and 44 one after another.

In [74]:
# Example 3 - breaking (to illustrate when it breaks)
arr=np.array([[9,6,2],
               [5,1,8],
               [6,4,0]])

np.place(arr,arr!=3,[0:4])
arr

SyntaxError: invalid syntax (<ipython-input-74-f5ac62b5f606>, line 6)

In this example, the error is generated. In this example we put a condition in which we used a range of number to replace specific numbers which is not valid. So, in order to get out we should replace the range of numbers by a single nmber or a list of numbers.

In [75]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dinmdohan813/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/dinmdohan813/numpy-array-operations


'https://jovian.ai/dinmdohan813/numpy-array-operations'

## Function 4 - np.extract

np.extract function is used to get the specific elements of the array which satisfy some specific condition

In [76]:
# Example 1 - working
a=np.array([[8,9,1],
            [3,7,0],
            [5,0,8]])
condition=a>3
condition

np.extract(condition,a)

array([8, 9, 7, 5, 8])

In this example we used np.extract function to extract the value which satisfy the contion of a>3.

In [78]:
# Example 2 - working
b= np.array([[7,3,11],
             [0,10,9],
             [33,77,2]])
c= np.array([[69,8,13],
             [76,7,56],
             [78,25,34]])
condition=np.mod((b,c),2)==0

np.extract(condition,(b,c))


array([ 0, 10,  2,  8, 76, 56, 78, 34])

In this example we used two arrays instead of single array and give a condition.While extracting the values we have to take care that we are giving only two arguments

In [79]:
# Example 3 - breaking (to illustrate when it breaks)
b= np.array([[7,3,11],
             [0,10,9],
             [33,77,2]])
c= np.array([[69,8,13],
             [76,7,56],
             [78,25,34]])
condition=np.mod((b,c),2)==0
np.extract(condition,b,c)

TypeError: _extract_dispatcher() takes 2 positional arguments but 3 were given

In this example the function breaks because we gave three arguments instead of two arguments in the extract function.This can be solved by givingonly two arguments in extract function.

This function is very useful when we have toobtain certain elements fromthe array satisfying certain conditions.

In [80]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dinmdohan813/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/dinmdohan813/numpy-array-operations


'https://jovian.ai/dinmdohan813/numpy-array-operations'

## Function 5 - np.clip

It is used to display values within a limit.

In [83]:
# Example 1 - working
b=np.array([[-3,3,6],
            [4,5,9]])
np.clip(b,1,5)


array([[1, 3, 5],
       [4, 5, 5]])

In this example we used clip function to limit the values of array within 1 and 5. If the values of array b are either less than 1 or greater than 5, it will display 1 and 5 respectively.

In [86]:
# Example 2 - working
a=np.array([[8,13,8],
            [5,9,0],
            [27,69,18]])
np.clip(a,3,4, out=a)

array([[4, 4, 4],
       [4, 4, 3],
       [4, 4, 4]])

In this example, we add another parameter out. It is used to preserve the value to the array.So when we again enter a then it gave the updated values then the old values.

In [87]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([[8,13,8],
            [5,9,0],
            [27,69,18]])
np.clip(a,3,4, out=b)

ValueError: operands could not be broadcast together with shapes (3,3) () () (2,3) 

In this example the operation has broken down because we tried to store the (3,3) in (2,3) order matrix. This is not valid. We must store to the same type of array because its type is being saved.

This function is quite useful in the view that we can limit our output within certain limits.

In [88]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dinmdohan813/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/dinmdohan813/numpy-array-operations


'https://jovian.ai/dinmdohan813/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
